language: cpp

#~ sudo: true
compiler:
  - clang
  - gcc

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - cmake-3.5


# if you need to install packages before installing
#~ before_install:
    #~ - sudo apt-get update -qq
    #~ - sudo apt-get install -qq liblapack.so 

install:
    - mkdir build
    - cd build
    - cmake ..
    - make

# run test
script:
    - cd build 
    - make test
