language: cpp

#~ sudo: true
compiler:
  - clang
  - gcc

# if you need to install packages before installing
#~ before_install:
    #~ - sudo apt-get update -qq
    #~ - sudo apt-get install -qq liblapack.so 

install:
    - mkdir build
    - cd build
    - cmake ..
    - make

# run tests
script:
    - cd build 
    - make test
