language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
            - cmake-data
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - cmake
            - cmake-data
      env: COMPILER=clang++-3.7

# if you need to install packages before installing
#~ before_install:
    #~ - sudo apt-get update -qq
    #~ - sudo apt-get install -qq liblapack.so 

install:
    - mkdir build
    - cd build
    - git clone https://github.com/FrescolinoGroup/cmake_extensions.git
    - wget https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp
    - export CPLUS_INCLUDE_PATH=$PWD:$CPLUS_INCLUDE_PATH
    - cmake .. -DCMAKE_MODULE_PATH=$PWD/cmake_extensions -DCMAKE_CXX_COMPILER=$COMPILER
    - make

# run test
script:
    - make test
